sudo: false

language: node_js

os:
  - linux
  # - osx

node_js:
  - 8
  - 7

cache:
  yarn: true
  directories:
    - node_modules

script:
  - node --version
  - yarn --version
  - yarn test

notifications:
  email: false
